# Generated by Django 5.2.17 on 2026-08-26 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='组名')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_project_groups', to=settings.AUTH_USER_MODEL, verbose_name='组长')),
                ('members', models.ManyToManyField(blank=True, related_name='project_groups', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '项目组',
                'verbose_name_plural': '项目组',
                'ordering': ('name', 'id'),
            },
        ),
    ]
