# Generated by Django 5.2.17 on 2026-09-12 02:23

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_copy_legacy_names'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
            ],
            options={
                'verbose_name': '项目组联系人',
                'verbose_name_plural': '项目组联系人',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_project_groups', to=settings.AUTH_USER_MODEL, verbose_name='项目组联系人'),
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=16, verbose_name='状态')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_group_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='join_requests', to='projects.projectgroup', verbose_name='项目组')),
            ],
            options={
                'verbose_name': '入组申请',
                'verbose_name_plural': '入组申请',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['group', 'status'], name='projects_gr_group_i_df119c_idx'), models.Index(fields=['applicant', 'status'], name='projects_gr_applica_0a58a9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('group', 'applicant'), name='unique_pending_group_join_request')],
            },
        ),
    ]
