# Generated by Django 5.2.17 on 2026-09-12 03:15

import projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcontact_alter_projectgroup_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='proposal',
            field=models.FileField(blank=True, help_text='支持 doc、docx、pdf；由项目组联系人维护，用于提交同行评审。', upload_to='project_proposals/%Y/%m/', validators=[projects.validators.validate_proposal_file], verbose_name='项目书'),
        ),
    ]
