# Generated by Django 5.2.17 on 2026-09-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectgroup_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='college',
            field=models.CharField(blank=True, max_length=128, verbose_name='学院'),
        ),
        migrations.CreateModel(
            name='ProjectAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='指导老师')),
                ('sort_order', models.PositiveSmallIntegerField(choices=[(0, '第 1 位'), (1, '第 2 位'), (2, '第 3 位')], default=0, verbose_name='顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='projects.projectgroup', verbose_name='项目组')),
            ],
            options={
                'verbose_name': '指导老师',
                'verbose_name_plural': '指导老师',
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('group', 'sort_order'), name='unique_project_advisor_slot'), models.CheckConstraint(condition=models.Q(('sort_order__lt', 3)), name='project_advisor_slot_within_three')],
            },
        ),
    ]
