# Generated by Django 5.2.17 on 2026-09-19 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectgroup_college_projectadvisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCreateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目组名称')),
                ('description', models.TextField(verbose_name='项目组描述')),
                ('college', models.CharField(blank=True, max_length=128, verbose_name='学院')),
                ('advisor_1', models.CharField(blank=True, max_length=128, verbose_name='指导老师 1')),
                ('advisor_2', models.CharField(blank=True, max_length=128, verbose_name='指导老师 2')),
                ('advisor_3', models.CharField(blank=True, max_length=128, verbose_name='指导老师 3')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=16, verbose_name='状态')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_create_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('created_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_request', to='projects.projectgroup', verbose_name='创建的项目组')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_group_create_requests', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '创建项目组申请',
                'verbose_name_plural': '创建项目组申请',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', 'created_at'], name='projects_gr_status_c40eb9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('applicant',), name='unique_pending_group_create_request')],
            },
        ),
    ]
