# Generated by Django 5.2.17 on 2026-09-22 13:04

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adminrole_preliminaryreviewerrole_reviewerrole_and_more'),
        ('projects', '0005_groupcreaterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
            ],
            options={
                'verbose_name': '项目组成员',
                'verbose_name_plural': '项目组成员',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
