# Generated by Django 5.2.17 on 2026-09-25 08:24

import core.storage
import projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='proposal',
            field=models.FileField(blank=True, help_text='支持 doc、docx、pdf；由项目组联系人维护，用于提交同行评审。', storage=core.storage.PrivateStorage(), upload_to=core.storage.NeutralUploadTo('project_proposals'), validators=[projects.validators.validate_proposal_file], verbose_name='项目书'),
        ),
    ]
