# Generated by Django 5.2.17 on 2026-09-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectgroup_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcreaterequest',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='项目组描述'),
        ),
        migrations.AlterField(
            model_name='groupjoinrequest',
            name='message',
            field=models.TextField(blank=True, max_length=2000, verbose_name='申请理由'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='简介'),
        ),
    ]
