# Generated by Django 5.2.17 on 2026-08-27 08:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类')),
                ('total_count', models.PositiveIntegerField(default=1, verbose_name='总量')),
                ('available_count', models.PositiveIntegerField(default=1, verbose_name='可借数量')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ('category', 'name', 'id'),
                'indexes': [models.Index(fields=['is_active', 'category', 'name'], name='equipment_e_is_acti_471e87_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('available_count__lte', models.F('total_count'))), name='equipment_available_lte_total')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='借用日期')),
                ('planned_return_date', models.DateField(verbose_name='计划归还日期')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='实际归还日期')),
                ('status', models.CharField(choices=[('borrowed', '已借用'), ('returned', '已归还')], default='borrowed', max_length=16, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_borrows', to=settings.AUTH_USER_MODEL, verbose_name='借用人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to='equipment.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备借用记录',
                'verbose_name_plural': '设备借用记录',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['borrower', 'status', '-created_at'], name='equipment_e_borrowe_b0b875_idx'), models.Index(fields=['equipment', 'status', '-created_at'], name='equipment_e_equipme_3839a4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actual_return_date__isnull', True), ('status', 'borrowed')), models.Q(('actual_return_date__isnull', False), ('status', 'returned')), _connector='OR'), name='borrow_status_matches_return_date')],
            },
        ),
    ]
