# Generated by Django 5.2.17 on 2026-09-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentborrow',
            name='remark',
            field=models.TextField(blank=True, max_length=1000, verbose_name='备注'),
        ),
    ]
