# Generated by Django 5.2.17 on 2026-09-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_copy_legacy_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reviewer',
            field=models.BooleanField(default=False, help_text='启用后可进入“评审”应用，审阅分配到自己的项目书并给出评审意见。', verbose_name='评审资格'),
        ),
    ]
