# Generated by Django 5.2.17 on 2026-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_reviewer',
            field=models.BooleanField(default=False, help_text='启用后可在“评审”中看到全部进行中的评审，并对其直接通过或打回：该票单独决定本轮结论，原本等待中的评审人随即被释放。与“评审资格”相互独立——只有同时具备评审资格，才会被随机抽为普通评审人。', verbose_name='超级评审资格'),
        ),
    ]
