# Generated by Django 5.2.17 on 2026-09-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_super_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_preliminary_reviewer',
            field=models.BooleanField(default=False, help_text='启用后可进入“评审”应用，对分配到的送审做初审：初审通过后才会随机分配评审人，初审打回则本轮不再分配评审人。与“评审资格”相互独立——同时具备时，本人初审通过的那一轮不会再抽到本人做正式评审。', verbose_name='初审资格'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_super_reviewer',
            field=models.BooleanField(default=False, help_text='启用后可在“评审”中看到全部进行中的评审（含初审中），并对其直接通过或打回：该票单独决定本轮结论，原本等待中的任务（初审一并）随即被释放。与“评审资格”相互独立——只有同时具备评审资格，才会被随机抽为普通评审人。', verbose_name='超级评审资格'),
        ),
    ]
