# Generated by Django 5.2.17 on 2026-09-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_preliminary_reviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(blank=True, help_text='可填写多项，用顿号或逗号分隔。', max_length=255, verbose_name='特长'),
        ),
    ]
