# Generated by Django 5.2.17 on 2026-09-22 13:04

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryReviewerRole',
            fields=[
            ],
            options={
                'verbose_name': '初审人',
                'verbose_name_plural': '初审人',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerRole',
            fields=[
            ],
            options={
                'verbose_name': '评审人',
                'verbose_name_plural': '评审人',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SuperReviewerRole',
            fields=[
            ],
            options={
                'verbose_name': '超级评审',
                'verbose_name_plural': '超级评审',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
