# Generated by Django 5.2.17 on 2026-09-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adminrole_preliminaryreviewerrole_reviewerrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='最多 1000 字。', max_length=1000, verbose_name='个人简介'),
        ),
    ]
