# Generated by Django 5.2.17 on 2026-09-23 05:48

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='不超过 2 MB。', upload_to='avatars/%Y/%m/', validators=[accounts.validators.validate_avatar], verbose_name='头像'),
        ),
    ]
