# Generated by Django 5.2.17 on 2026-09-23 06:01

import accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='不超过 5 MB。', upload_to='gallery/%Y/%m/', validators=[accounts.validators.validate_gallery_image], verbose_name='图像')),
                ('layout', models.CharField(choices=[('normal', '普通'), ('wide', '大图'), ('full', '整行')], default='normal', max_length=8, verbose_name='排布')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='accounts.profile', verbose_name='个人资料')),
            ],
            options={
                'verbose_name': '图册图像',
                'verbose_name_plural': '图册图像',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
