# Generated by Django 5.2.17 on 2026-09-25 08:24

import accounts.validators
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='不超过 5 MB。', storage=core.storage.PrivateStorage(), upload_to=core.storage.NeutralUploadTo('gallery'), validators=[accounts.validators.validate_gallery_image], verbose_name='图像'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='不超过 2 MB。', storage=core.storage.PrivateStorage(), upload_to=core.storage.NeutralUploadTo('avatars'), validators=[accounts.validators.validate_avatar], verbose_name='头像'),
        ),
    ]
