# Generated by Django 5.2.17 on 2026-10-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_galleryimage_sha256_profile_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receives_preliminary_tasks',
            field=models.BooleanField(default=True, help_text='关闭后不再被抽为初审人，也不会出现在改派候选里；初审资格不受影响。手上还有未完成的初审任务时关不掉。', verbose_name='接收初审任务'),
        ),
        migrations.AddField(
            model_name='user',
            name='receives_review_tasks',
            field=models.BooleanField(default=True, help_text='关闭后不再被抽为评审人，也不会出现在改派候选里；评审资格不受影响。手上还有未完成的评审任务时关不掉。', verbose_name='接收评审任务'),
        ),
    ]
