# Generated by Django 5.2.17 on 2026-09-23 11:15

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='英文名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_discussion_boards', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '社团空间板块',
                'verbose_name_plural': '社团空间板块',
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussion_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='discussion.board', verbose_name='板块')),
            ],
            options={
                'verbose_name': '社团空间帖子',
                'verbose_name_plural': '社团空间帖子',
                'ordering': ('-is_pinned', '-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussion_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussion.post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '社团空间评论',
                'verbose_name_plural': '社团空间评论',
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='discussion_board_name_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['board', '-is_pinned', '-created_at', '-id'], name='discussion_post_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='discussion_comment_post_idx'),
        ),
    ]
