# Generated by Django 5.2.17 on 2026-09-23 13:18

import discussion.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_board_chinese_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='discussion/%Y/%m/', validators=[discussion.validators.validate_post_image], verbose_name='帖子图片')),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='discussion.post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '帖子图片',
                'verbose_name_plural': '帖子图片',
                'ordering': ('created_at', 'pk'),
            },
        ),
    ]
