# Generated by Django 5.2.17 on 2026-09-23 14:28

import discussion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=discussion.validators.post_image_upload_to, validators=[discussion.validators.validate_post_image], verbose_name='帖子图片'),
        ),
    ]
