# Generated by Django 5.2.17 on 2026-09-24 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_alter_postimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'default_manager_name': 'objects',
                'ordering': ('created_at', 'pk'),
                'verbose_name': '社团空间评论',
                'verbose_name_plural': '社团空间评论',
            },
        ),
        # 软删除：行与内容都留着，只把删除时间与删除人记下来。
        migrations.AddField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_comments', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
    ]
