# Generated by Django 5.2.17 on 2026-09-25 08:24

import core.storage
import discussion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_comment_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(storage=core.storage.PrivateStorage(), upload_to=core.storage.NeutralUploadTo('discussion'), validators=[discussion.validators.validate_post_image], verbose_name='帖子图片'),
        ),
    ]
