# Generated by Django 5.2.17 on 2026-08-25 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('scope', models.CharField(choices=[('public', '公开'), ('internal', '内部')], default='public', max_length=16, verbose_name='可见范围')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_notices', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '通知公告',
                'verbose_name_plural': '通知公告',
                'ordering': ('-is_pinned', '-published_at', '-id'),
                'indexes': [models.Index(fields=['scope', '-published_at'], name='notices_not_scope_3fb660_idx'), models.Index(fields=['scope', '-is_pinned', '-published_at'], name='notices_not_scope_183818_idx')],
            },
        ),
    ]
