# Generated by Django 5.2.17 on 2026-08-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='visible_groups',
            field=models.ManyToManyField(blank=True, help_text='内部通知必须至少选择一个用户组；属于任一所选用户组的成员可以查看。', related_name='visible_notices', to='auth.group', verbose_name='可查看用户组'),
        ),
    ]
