# Generated by Django 5.2.17 on 2026-08-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('notices', '0002_notice_visible_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='notices', to='media.mediafile', verbose_name='配图/视频'),
        ),
    ]
