# Generated by Django 5.2.17 on 2026-09-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notices', '0003_notice_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='scope',
            field=models.CharField(choices=[('public', '公开'), ('internal', '内部'), ('contacts', '仅联系人可见')], default='public', max_length=16, verbose_name='可见范围'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='visible_groups',
            field=models.ManyToManyField(blank=True, help_text='仅“内部”通知需要选择用户组；属于任一所选用户组的成员可以查看。“公开”和“仅联系人可见”通知无需选择。', related_name='visible_notices', to='auth.group', verbose_name='可查看用户组'),
        ),
    ]
