# Generated by Django 5.2.17 on 2026-10-02 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0008_postimage_sha256'),
        ('notices', '0005_noticeread'),
        ('projects', '0009_projectgroup_sha256'),
        ('reviews', '0010_archivedproposal_sha256_reviewtask_sha256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mention', '提及'), ('review_preliminary', '初审任务'), ('review', '评审任务'), ('review_result', '评审结果'), ('join_request', '入组申请'), ('join_result', '入组结果'), ('create_request', '建组申请'), ('create_result', '建组结果')], max_length=20, verbose_name='类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='产生时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discussion.comment', verbose_name='评论')),
                ('create_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.groupcreaterequest', verbose_name='建组申请')),
                ('join_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.groupjoinrequest', verbose_name='入组申请')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discussion.post', verbose_name='帖子')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='收件人')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reviews.projectsubmission', verbose_name='送审轮次')),
            ],
            options={
                'verbose_name': '站内消息',
                'verbose_name_plural': '站内消息',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notices_mes_recipie_36d97e_idx'), models.Index(fields=['recipient', '-created_at', '-id'], name='notices_mes_recipie_12624e_idx')],
            },
        ),
    ]
