# Generated by Django 5.2.17 on 2026-10-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(max_length=20000, verbose_name='正文'),
        ),
    ]
