# Generated by Django 5.2.17 on 2026-09-12 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_projectgroup_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1, verbose_name='评审轮次')),
                ('message', models.TextField(blank=True, verbose_name='提交说明')),
                ('status', models.CharField(choices=[('pending', '评审中'), ('approved', '已通过'), ('needs_revision', '需修改')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='projects.projectgroup', verbose_name='项目组')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '项目书送审',
                'verbose_name_plural': '项目书送审',
                'ordering': ('-submitted_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待评审'), ('completed', '已完成')], default='pending', max_length=16, verbose_name='状态')),
                ('decision', models.CharField(blank=True, choices=[('approve', '通过'), ('revise', '需修改')], max_length=16, verbose_name='评审决定')),
                ('comment', models.TextField(blank=True, verbose_name='评审意见')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments', to=settings.AUTH_USER_MODEL, verbose_name='评审人')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reviews.projectsubmission', verbose_name='送审')),
            ],
            options={
                'verbose_name': '评审任务',
                'verbose_name_plural': '评审任务',
                'ordering': ('status', '-assigned_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='projectsubmission',
            index=models.Index(fields=['group', 'status'], name='reviews_pro_group_i_391d89_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='reviews_pro_status_27bd5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectsubmission',
            constraint=models.UniqueConstraint(fields=('group', 'round'), name='unique_group_submission_round'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['reviewer', 'status'], name='reviews_rev_reviewe_73b0d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(fields=('submission', 'reviewer'), name='unique_submission_reviewer'),
        ),
    ]
