# Generated by Django 5.2.17 on 2026-09-14 13:21

import django.db.models.deletion
import projects.validators
import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectgroup_proposal'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='review_type',
            field=models.CharField(blank=True, choices=[('competition_project', '竞赛立项'), ('competition_provincial', '竞赛省赛'), ('competition_national', '竞赛国赛'), ('innovation_start', '大创立项'), ('innovation_midterm', '大创中期'), ('innovation_final', '大创结题')], default='', help_text='决定本轮需要几名评审人；升级前创建的送审留空，沿用两人制。', max_length=32, verbose_name='评审类型'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='annotated_file',
            field=models.FileField(blank=True, help_text='选填；支持 doc、docx、pdf。请勿在文件属性中保留可识别个人身份的信息。', upload_to=reviews.models.upload_annotated_proposal, validators=[projects.validators.validate_proposal_file], verbose_name='批注版项目书'),
        ),
        migrations.CreateModel(
            name='ArchivedProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=reviews.models.upload_archived_proposal, verbose_name='批注版项目书')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='归档时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_proposals', to='projects.projectgroup', verbose_name='项目组')),
                ('source_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_proposals', to='reviews.reviewassignment', verbose_name='来源评审任务')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_proposals', to='reviews.projectsubmission', verbose_name='送审')),
            ],
            options={
                'verbose_name': '批注版项目书归档',
                'verbose_name_plural': '批注版项目书归档',
                'ordering': ('-archived_at', '-id'),
                'indexes': [models.Index(fields=['group', '-archived_at'], name='reviews_arc_group_i_3262b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_assignment',), name='unique_archived_proposal_assignment')],
            },
        ),
    ]
