# Generated by Django 5.2.17 on 2026-09-15 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_projectsubmission_review_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='请假开始')),
                ('ends_at', models.DateTimeField(verbose_name='请假结束')),
                ('reason', models.TextField(blank=True, verbose_name='事由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, help_text='首次登记该请假的账号：本人自助登记时为自己，管理员代登记时为该管理员。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_reviewer_leaves', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewer_leaves', to=settings.AUTH_USER_MODEL, verbose_name='评审人')),
            ],
            options={
                'verbose_name': '评审人请假',
                'verbose_name_plural': '评审人请假',
                'ordering': ('-starts_at', '-id'),
                'indexes': [models.Index(fields=['reviewer', 'starts_at', 'ends_at'], name='reviews_rev_reviewe_c83db1_idx'), models.Index(fields=['starts_at', 'ends_at'], name='reviews_rev_starts__1f97a0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='reviewer_leave_ends_after_starts')],
            },
        ),
    ]
