# Generated by Django 5.2.17 on 2026-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewerleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='is_override',
            field=models.BooleanField(default=False, help_text='该行来自超级评审的一票决定：本轮结论由它单独敲定，等待中的评审人随即被释放。', verbose_name='超级评审决定'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='status',
            field=models.CharField(choices=[('pending', '待评审'), ('completed', '已完成'), ('released', '已释放')], default='pending', max_length=16, verbose_name='状态'),
        ),
    ]
