# Generated by Django 5.2.17 on 2026-09-16 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviewassignment_is_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='status',
            field=models.CharField(choices=[('preliminary_pending', '初审中'), ('pending', '评审中'), ('approved', '已通过'), ('needs_revision', '需修改')], default='preliminary_pending', help_text='新建的轮次从「初审中」开始；初审通过后才进入「评审中」。', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='is_override',
            field=models.BooleanField(default=False, help_text='该行来自超级评审的一票决定：本轮结论由它单独敲定，等待中的任务（初审一并）随即被释放。', verbose_name='超级评审决定'),
        ),
        migrations.CreateModel(
            name='PreliminaryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待初审'), ('completed', '已初审'), ('released', '已释放')], default='pending', max_length=16, verbose_name='状态')),
                ('decision', models.CharField(blank=True, choices=[('approve', '通过'), ('revise', '需修改')], max_length=16, verbose_name='初审决定')),
                ('comment', models.TextField(blank=True, verbose_name='初审意见')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('reviewer', models.ForeignKey(help_text='须有初审资格（User.is_preliminary_reviewer）。', on_delete=django.db.models.deletion.PROTECT, related_name='preliminary_reviews', to=settings.AUTH_USER_MODEL, verbose_name='初审人')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_review', to='reviews.projectsubmission', verbose_name='送审')),
            ],
            options={
                'verbose_name': '初审任务',
                'verbose_name_plural': '初审任务',
                'ordering': ('-assigned_at', '-id'),
                'indexes': [models.Index(fields=['reviewer', 'status'], name='reviews_pre_reviewe_1dcb08_idx')],
            },
        ),
    ]
