# Generated by Django 5.2.17 on 2026-09-25 08:24

import core.storage
import projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedproposal',
            name='file',
            field=models.FileField(storage=core.storage.PrivateStorage(), upload_to=core.storage.NeutralUploadTo('review_archives'), verbose_name='批注版项目书'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='annotated_file',
            field=models.FileField(blank=True, help_text='选填；支持 doc、docx、pdf。请勿在文件属性中保留可识别个人身份的信息。', storage=core.storage.PrivateStorage(), upload_to=core.storage.NeutralUploadTo('review_annotations'), validators=[projects.validators.validate_proposal_file], verbose_name='批注版项目书'),
        ),
    ]
