# Generated by Django 5.2.17 on 2026-09-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_archivedproposal_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='message',
            field=models.TextField(blank=True, max_length=5000, verbose_name='提交说明'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='comment',
            field=models.TextField(blank=True, max_length=5000, verbose_name='意见'),
        ),
    ]
