# Generated by Django 5.2.17 on 2026-09-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_projectsubmission_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerleave',
            name='reason',
            field=models.TextField(blank=True, max_length=500, verbose_name='事由'),
        ),
    ]
