# Generated by Django 5.2.17 on 2026-08-26 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='竞赛名称')),
                ('description', models.TextField(verbose_name='竞赛说明')),
                ('deadline', models.DateTimeField(verbose_name='报名截止时间')),
                ('team_size', models.CharField(blank=True, help_text='例如：2-5 人；仅作展示说明，具体成员由报名时选择。', max_length=100, verbose_name='组队人数要求')),
                ('is_open', models.BooleanField(default=True, verbose_name='报名开放')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_competitions', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '竞赛信息',
                'verbose_name_plural': '竞赛信息',
                'ordering': ('-is_open', 'deadline', '-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CompetitionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='competitions.competition', verbose_name='竞赛')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_registrations', to='projects.projectgroup', verbose_name='项目组')),
                ('members', models.ManyToManyField(related_name='competition_registrations', to=settings.AUTH_USER_MODEL, verbose_name='参赛成员')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_registrations_created', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '竞赛报名',
                'verbose_name_plural': '竞赛报名',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['is_open', 'deadline'], name='competition_is_open_8751a6_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['-published_at'], name='competition_publish_edb5ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitionregistration',
            constraint=models.UniqueConstraint(fields=('competition', 'group'), name='unique_competition_group_registration'),
        ),
    ]
