# Generated by Django 5.2.17 on 2026-09-12 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_team_leader(apps, schema_editor):
    """Existing registrations predate team_leader; default it to the registrar."""
    CompetitionRegistration = apps.get_model("competitions", "CompetitionRegistration")
    CompetitionRegistration.objects.filter(team_leader__isnull=True).update(
        team_leader=F("registered_by")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionregistration',
            name='team_leader',
            field=models.ForeignKey(blank=True, help_text='由联系人在所选项目组成员中指定，可以是联系人本人。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_competition_registrations', to=settings.AUTH_USER_MODEL, verbose_name='竞赛组长'),
        ),
        migrations.RunPython(backfill_team_leader, migrations.RunPython.noop),
    ]
