# Generated by Django 5.2.17 on 2026-09-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competitionregistration_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionregistration',
            name='remark',
            field=models.TextField(blank=True, max_length=2000, verbose_name='备注'),
        ),
    ]
