# Generated by Django 5.2.17 on 2026-10-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competitionregistration_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='竞赛说明'),
        ),
    ]
