# Generated by Django 5.2.17 on 2026-08-25 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='页面标识')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('is_published', models.BooleanField(default=False, verbose_name='已发布')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('attachments', models.ManyToManyField(blank=True, related_name='content_pages', to='media.mediafile', verbose_name='配图/视频')),
            ],
            options={
                'verbose_name': '公开内容页',
                'verbose_name_plural': '公开内容页',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='奖项名称')),
                ('competition', models.CharField(max_length=200, verbose_name='赛事名称')),
                ('year', models.PositiveIntegerField(verbose_name='年份')),
                ('level', models.CharField(blank=True, max_length=100, verbose_name='获奖级别')),
                ('winners', models.TextField(blank=True, verbose_name='获奖人/团队')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('attachments', models.ManyToManyField(blank=True, related_name='awards', to='media.mediafile', verbose_name='奖状/现场图/视频')),
            ],
            options={
                'verbose_name': '历年获奖',
                'verbose_name_plural': '历年获奖',
                'ordering': ('-year', '-created_at', '-id'),
                'indexes': [models.Index(fields=['-year', '-created_at'], name='content_awa_year_9ee570_idx')],
            },
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, verbose_name='简介文字')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showcase_entries', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showcases', to='media.mediafile', verbose_name='展示照片/视频')),
            ],
            options={
                'verbose_name': '成员风采',
                'verbose_name_plural': '成员风采',
                'ordering': ('sort_order', 'member__username', '-id'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='content_sho_is_acti_70b585_idx')],
            },
        ),
    ]
