# Generated by Django 5.2.17 on 2026-09-14 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='说明文字')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('image', models.ForeignKey(limit_choices_to={'kind': 'image'}, on_delete=django.db.models.deletion.PROTECT, related_name='home_slides', to='media.mediafile', verbose_name='图片')),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
                'ordering': ('sort_order', 'pk'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='content_hom_is_acti_8cfd02_idx')],
            },
        ),
    ]
