# Generated by Django 5.2.17 on 2026-10-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_award_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='winners',
            field=models.TextField(max_length=500, verbose_name='获奖人/团队'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=models.TextField(max_length=20000, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='intro',
            field=models.TextField(blank=True, max_length=1000, verbose_name='简介文字'),
        ),
    ]
